// WebMCP tools: lets an AI agent in the browser ask this page for facts and actions directly instead of
// scraping it (https://developer.chrome.com/docs/ai/webmcp). Only registered where the browser offers
// `modelContext`; everywhere else this file does nothing. All data comes from the same places the page
// uses — latest.json and changelog.md on this origin — so tools and page can never disagree.
(function () {
  'use strict';

  var mc = (typeof document !== 'undefined' && document.modelContext) ||
    (typeof navigator !== 'undefined' && navigator.modelContext);
  if (!mc || typeof mc.registerTool !== 'function') return;

  // Facts from site.json (generated by build.py).
  var FACTS = {
    "name": "Brutus",
    "summary": "Brutus is a free, open-source (MIT) alarm clock for Android 8.0 and later. A ringing alarm only stops once you complete the challenges you chose for it: solve math problems, shake the phone, or scan a QR code you placed somewhere else in your home — in any combination, one after the other. Hardcore mode keeps the alarm at full volume while it rings; Ultra Hardcore mode re-rings 10 and 15 minutes later unless you walk 30 steps. It also has a world clock, stopwatch, timer and a home-screen widget, runs in English and German, has no ads or tracking, and stays offline unless you switch on its update check, which then reads the newest version number once a day and notifies you. Distributed as a signed APK through GitHub Releases.",
    "requirements": {
      "android": "Android 8.0+"
    },
    "platforms": [],
    "features": [
      "Wake-up challenges: math problems, shaking the phone and scanning a QR code, combinable and run in sequence",
      "Three math difficulties and three shake sensitivities per alarm",
      "Hardcore mode: alarm volume stays at maximum and the volume keys do nothing while it rings",
      "Ultra Hardcore mode: two follow-up alarms after dismissal, cancelled only by walking 30 steps",
      "Eleven alarm sounds synthesized on the device, plus the system alarm tone and a silent option",
      "Sunrise pre-alarm: screen brightens over the 10 minutes before the alarm",
      "Slide-to-snooze with configurable snooze length, or no snooze at all",
      "Test mode to try a wake-up chain without setting a real alarm",
      "World clock, stopwatch and timer",
      "Home-screen widget with the next alarm and a countdown",
      "Alarms survive reboots and Doze; banners warn when the system would block them",
      "English and German, including per-app language on Android 13+",
      "Opt-in update check: a daily look at the newest version, a notification and a banner when one is out",
      "No ads, no tracking; offline by default"
    ],
    "limits": [
      "Android only; not on Google Play — distributed as an APK through GitHub Releases.",
      "The QR challenge needs Google Play Services, which delivers the barcode model; math and shake work without it.",
      "Available in English and German only.",
      "Android offers no way to truly lock the volume: Hardcore mode snaps it back to maximum and swallows the volume keys while the alarm rings.",
      "It does not download or install updates by itself — it only tells you, and you install the new APK over the old one."
    ],
    "targets": [
      "android"
    ],
    "signing": [
      {
        "what": "Signing certificate SHA-256",
        "value": "69d67a10a826cf4050da4b271af9b5ed500c962bfab07a8f8fe863e3d7600382"
      }
    ],
    "links": {
      "page": "https://brutus.celox.io/",
      "download": "https://brutus.celox.io/download",
      "latest": "https://brutus.celox.io/latest.json",
      "markdown": "https://brutus.celox.io/index.md",
      "changelog": "https://brutus.celox.io/changelog.md",
      "skill": "https://brutus.celox.io/skills/get-brutus/SKILL.md",
      "source": "https://github.com/pepperonas/brutus",
      "licence": "https://github.com/pepperonas/brutus/blob/main/LICENSE"
    }
  };
  var SITE = FACTS.links.page.replace(/\/$/, '');
  var LANGS = ["en", "de", "es", "it", "fr"];

  function latest(signal) {
    return fetch('/latest.json', { cache: 'no-cache', signal: signal }).then(function (r) {
      if (!r.ok) throw new Error('latest.json: HTTP ' + r.status);
      return r.json();
    });
  }
  function json(v) { return JSON.stringify(v, null, 2); }
  var READ = { readOnlyHint: true };

  var tools = [
    {
      name: 'get_app_facts',
      description: 'What Brutus is: a one-paragraph summary, requirements, supported platforms, ' +
        'features, limits and the important links (download, source, changelog, licence).',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      annotations: READ,
      execute: function () { return Promise.resolve(json(FACTS)); }
    },
    {
      name: 'get_latest_release',
      description: 'The newest release of Brutus: version, publication date, release notes URL ' +
        'and every file with its download URL, size in bytes and SHA-256.',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      annotations: READ,
      execute: function (_input, opts) {
        return latest(opts && opts.signal).then(function (d) {
          return json({ version: d.version, published: d.published, notes: d.notes, assets: d.assets ||
            [{ target: FACTS.targets[0], name: d.name, url: d.url, size: d.size, sha256: d.sha256 }] });
        });
      }
    },
    {
      name: 'get_download_url',
      description: 'The direct download URL of the newest Brutus file for a platform (android), plus ' +
        'the stable link that always redirects to the newest file.',
      inputSchema: {
        type: 'object',
        properties: { platform: { type: 'string', enum: FACTS.targets, description: 'Target platform; default: ' + FACTS.targets[0] + '.' } },
        additionalProperties: false
      },
      annotations: READ,
      execute: function (input, opts) {
        return latest(opts && opts.signal).then(function (d) {
          var assets = d.assets || [{ target: FACTS.targets[0], name: d.name, url: d.url, size: d.size }];
          var want = (input && input.platform) || assets[0].target;
          var a = assets.filter(function (x) { return x.target === want; })[0] || assets[0];
          return json({ version: d.version, platform: a.target, file: a.name, url: a.url, size: a.size,
            stable_link: SITE + '/download/' + a.target });
        });
      }
    },
    {
      name: 'get_checksums',
      description: 'How to verify a downloaded Brutus file: the SHA-256 of every file of the newest release ' +
        'and the fixed signing facts.',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      annotations: READ,
      execute: function (_input, opts) {
        return latest(opts && opts.signal).then(function (d) {
          var assets = d.assets || [{ name: d.name, sha256: d.sha256 }];
          return json({ version: d.version,
            files: assets.map(function (a) { return { name: a.name, sha256: a.sha256 }; }),
            signing: FACTS.signing });
        });
      }
    },
    {
      name: 'get_changelog',
      description: 'The most recent entries of the Brutus changelog as Markdown.',
      inputSchema: {
        type: 'object',
        properties: { versions: { type: 'integer', minimum: 1, maximum: 10, description: 'How many versions (default 3).' } },
        additionalProperties: false
      },
      annotations: READ,
      execute: function (input, opts) {
        var n = Math.min(10, Math.max(1, (input && input.versions) || 3));
        return fetch('/changelog.md', { cache: 'no-cache', signal: opts && opts.signal }).then(function (r) {
          if (!r.ok) throw new Error('changelog.md: HTTP ' + r.status);
          return r.text();
        }).then(function (md) {
          var parts = md.split(/\n(?=## \[)/).slice(1).filter(function (s) { return !/^## \[Unreleased\]\s*$/.test(s.trim()); });
          return parts.slice(0, n).join('\n').trim();
        });
      }
    },
    {
      name: 'set_page_language',
      description: 'Show this page in another language (English, German, Spanish, Italian or French).',
      inputSchema: {
        type: 'object',
        properties: { language: { type: 'string', enum: LANGS, description: 'ISO 639-1 code.' } },
        required: ['language'],
        additionalProperties: false
      },
      annotations: { readOnlyHint: false },
      execute: function (input) {
        if (LANGS.indexOf(input.language) < 0) throw new Error('unsupported language: ' + input.language);
        if (typeof window.SITE_setLanguage === 'function') window.SITE_setLanguage(input.language);
        return Promise.resolve('Page language set to ' + input.language + '.');
      }
    }
  ];

  tools.forEach(function (t) {
    try { mc.registerTool(t); } catch (e) { /* a browser with an older WebMCP shape: skip that tool */ }
  });
})();
